set_lock_state:
  name: Set lock state
  description: Set the lock state of a flap.
  fields:
    flap_id:
      name: Flap ID
      description: The ID of the flap to set the lock state for.
      example: "12345"
      required: true
      selector:
        text: {}
    state:
      name: State
      description: The lock state to set.
      example: "LOCKED_IN"
      required: true
      selector:
        text: {}

set_pet_location:
  name: Set pet location
  description: Set the location of a pet.
  fields:
    pet_id:
      name: Pet ID
      description: The ID of the pet to set the location for.
      example: "12345"
      required: true
      selector:
        text: {}
    where:
      name: Location
      description: The location to set.
      example: "INSIDE"
      required: true
      selector:
        text: {}

set_indoor_only_mode:
  name: Set indoor only mode
  description: Set indoor only mode for a pet.
  fields:
    pet_id:
      name: Pet ID
      description: The ID of the pet to set indoor only mode for.
      example: "12345"
      required: true
      selector:
        text: {}
    enabled:
      name: Enabled
      description: Whether to enable or disable indoor only mode.
      example: true
      required: true
      selector:
        boolean: {}
